# Change these first
owner: emrusz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Forgejo
    url: https://git.rusz.dev
  - name: Grocy
    url: https://grocy.beans.team
  - name: LanguageTool
    url: https://lt.rusz.dev/v2/languages
  - name: Matrix
    url: https://element.rusz.dev
  - name: Minecraft
    url: https://horseplay.space
  - name: Nextcloud
    url: https://cloud.beans.team
  - name: Piped
    url: https://piped.beans.team
  - name: Rallly
    url: https://rallly.rusz.dev
  - name: "rusz.dev"
    url: https://rusz.dev
  - name: Vikunja
    url: https://todo.rusz.dev

assignees:
  - emrusz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rusz.dev
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "rusz.dev status"
  introTitle: "Homelab services provided by rusz.dev."
  introMessage: "View the about page for more information."
  theme: dark
  navbar:
    - title: Status
      href: https://status.rusz.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: About
      href: https://rusz.dev/about

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
