# Change these first
owner: ethanrusz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Forgejo
    url: https://git.beans.team
  - name: Grocy
    url: https://grocy.beans.team
  - name: LanguageTool
    url: https://lt.beans.team/v2/languages
  - name: Minecraft
    url: https://horseplay.space
  - name: Nextcloud
    url: https://cloud.beans.team
  - name: Piped
    url: https://piped.beans.team
  - name: Rallly
    url: https://rallly.beans.team
  - name: "rusz.dev"
    url: https://rusz.dev

assignees:
  - ethanrusz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ruszdev Status
  introTitle: "Current beans.team services."
  introMessage: "View the about page for more information."
  theme: dark
  navbar:
    - title: Status
      href: https://ethanrusz.github.io/status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: About
      href: https://rusz.dev/about

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
